MetaDataFormat: "yaml"

title: "睿"
baseurl: "http://z-rui.github.io/"
defaultContentLanguage: "zh"
copyright: |
    &copy; 2015---2018.
    使用[Hugo](http://gohugo.io)构建.
theme: "hugo-theme-bootstrap4-blog"

params:
    author: rui
    header_visible: false
    sidebar:
        about: |
            <iframe src="https://ghbtns.com/github-btn.html?user=z-rui&type=follow&count=true&size=large" frameborder="0" scrolling="0" width="220px" height="30px"></iframe>
        num_recent_posts: 4

# vim: ts=4:sw=4:et
